version: '3.4'

services:
  consumermanager:
    container_name: api-service
    image: ${DOCKER_REGISTRY-}consumermanager
    build:
      context: .
      dockerfile: ConsumerManager/Dockerfile
    ports:
      - 7080:80
      - 7000:443
    depends_on:
      - database
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  database:
    container_name: database
    image: postgis/postgis:14-3.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres

volumes:
  data:
    name: consumer-database
    driver: local
    driver_opts:
      o: bind
      type: none
      device: data
