name: Continuous Integration Pipeline
on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  setup:
    name: Setup workspace
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.names.outputs.name }}
      environment: ${{ steps.names.outputs.environment }}
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
      - id: names
        name: Name for GitHub Environment
        run: |
          environtment=Development
          if [ "$BRANCH" = "main" ]; then
            name=production
            environment=Production
          elif [ "$BRANCH" = "staging" ]; then
            environment=${BRANCH^}
          fi
          echo environment=$environment >> "$GITHUB_OUTPUT"

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing .NET and dependencies
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
          cache: true
      - run: dotnet build API
        working-directory: API
